### ISSUE TITLE
Submission Checklist - Preparing your material

### ISSUE THREAD

**Issue by kescobo** [Klepac-Ceraj-Lab/EEGMicrobiome#8]
https://www.nature.com/neuro/submission-guidelines/preparing-your-submission

## What your submission should include

- [ ] Manuscript file [including Methods, Figures and Extended Data if applicable]
- [ ] Cover letter 
- [ ] Supplementary Information – optional; see details below.
- [ ] Manuscript file

## The manuscript file must contain:

- [ ] Names and affiliations of all co-authors (if you choose [double-blind peer review](https://www.nature.com/neuro/submission-guidelines/dbpr), you should put this information in the cover letter). The primary affiliation for each author should be the institution where the majority of their work was done. If an author has subsequently moved, the current address may also be stated. Large Language Models (LLMs), such as [ChatGPT](https://openai.com/blog/chatgpt/), do not currently satisfy our [authorship criteria](https://www.nature.com/nature-portfolio/editorial-policies/authorship). Notably an attribution of authorship carries with it accountability for the work, which cannot be effectively applied to LLMs. Use of an LLM should be properly documented in the Methods section (and if a Methods section is not available, in a suitable alternative part) of the manuscript.
- [ ] A detailed description of the findings of the work, including sufficient information on methods and materials which would enable replication of the study by a fellow expert. 
- [ ] A reference list.
- [ ] OPTIONAL Extended Data – Extended Data figures and tables are online-only display items that provide essential background to the main paper but are not included as main display items due to space constraints or being of interest only to specialists. A maximum of ten Extended Data display items is permitted. 
- [ ] Methods & Protocols

- [ ] The Methods section should be written as concisely as possible but should contain all elements necessary to allow interpretation and replication of the results. The Methods sections of all original research papers will appear in all online versions. 

- [ ] Authors are encouraged to deposit the step-by-step protocols used in their study to [www.protocols.io](https://www.protocols.io/), an open repository of scientific protocols of Springer Nature. Protocols deposited by the authors will be linked to the online Methods section upon publication.

## Cover letter

- [ ] The cover letter should explain the importance of the work, and why you consider it appropriate for the diverse readership of Nature Neuroscience. 

The cover letter should: 

- [ ] Disclose details of any related manuscripts that all authors have under consideration or in press elsewhere.
- [ ] Let us know whether you have had any prior discussions with a Nature Neuroscience editor about the work described in the manuscript.
- [ ] If choosing [double-blind peer review](https://www.nature.com/neuro/submission-guidelines/dbpr), include the affiliation and contact information for all authors (instead of putting it in the manuscript file). 
- [ ] OPTIONAL. Provide the name and institution of reviewers you would like to recommend and/or people you would like to be excluded from peer review (explaining why).
- [ ] The cover letter is not seen by peer reviewers.
- [ ] Supplementary Information

- [ ] Any information (including display items) not directly related to the description of the main findings, but needed to properly understand and replicate the study, should be included in supplementary information files.

- [ ] Only Supplementary Information that is relevant to the conclusions of the paper should be included.

The Supplementary Information document will be sent to peer reviewers alongside the manuscript file.
